# Generated by Django 5.0.7 on 2024-07-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_factura',
            fields=[
                ('id_producto_per', models.IntegerField(auto_created=True)),
                ('id_factura_per', models.IntegerField(auto_created=True)),
                ('id_detalle_factura', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal_producto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_iva', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'detalle_factura',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('xml', models.FileField(blank=True, null=True, upload_to='static/email/xml/')),
                ('ride', models.FileField(blank=True, null=True, upload_to='static/email/pdf/')),
            ],
            options={
                'db_table': 'documento',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero_factura', models.IntegerField(auto_created=True)),
                ('id_documento_per', models.IntegerField(auto_created=True)),
                ('id_forma_pago_per', models.IntegerField(auto_created=True)),
                ('id_usuario_per', models.IntegerField(auto_created=True)),
                ('id_cliente_per', models.IntegerField(auto_created=True)),
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('clave_acceso', models.CharField(max_length=49)),
                ('fecha', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_iva', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
