# Generated by Django 5.0.7 on 2024-07-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('licencia_per', models.CharField(max_length=20, unique=True)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('tipo_contribuyente', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static/logos/')),
                ('lleva_contabilidad', models.BooleanField(default=False)),
                ('firma_electronica', models.FileField(blank=True, null=True, upload_to='static/firmas/')),
                ('contrasena_firma_electronica', models.CharField(max_length=255)),
                ('desarrollo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
    ]
