# Generated by Django 5.0.7 on 2024-07-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('numero_identificacion', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('tipo_persona', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Detalle_empresa_cliente',
            fields=[
                ('id_cliente_per', models.IntegerField(auto_created=True)),
                ('id_empresa_per', models.IntegerField(auto_created=True)),
                ('id_detalle_empresa_cliente', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detalle_empresa_cliente',
            },
        ),
        migrations.CreateModel(
            name='Detalle_empresa_iva',
            fields=[
                ('id_empresa_per', models.IntegerField(auto_created=True)),
                ('id_iva_per', models.IntegerField(auto_created=True)),
                ('id_detalle_empresa_iva', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detalle_empresa_iva',
            },
        ),
        migrations.CreateModel(
            name='Detalle_empresa_producto',
            fields=[
                ('id_empresa_per', models.IntegerField(auto_created=True)),
                ('id_producto_per', models.IntegerField(auto_created=True)),
                ('id_detalle_empresa_producto', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detalle_empresa_producto',
            },
        ),
        migrations.CreateModel(
            name='Forma_pago',
            fields=[
                ('id_forma_pago', models.AutoField(primary_key=True, serialize=False)),
                ('forma_pago', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'forma_pago',
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('licencia', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'licencias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_iva_per', models.IntegerField(auto_created=True)),
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
