# Generated by Django 5.0.7 on 2024-07-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cliente_detalle_empresa_cliente_detalle_empresa_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id_documento_per',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id_forma_pago_per',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
