# Generated by Django 5.0.7 on 2024-07-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_factura_id_documento_per_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
