# Generated by Django 5.0.7 on 2024-07-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_factura_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='total_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
