# Generated by Django 5.0.7 on 2024-08-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_factura_id_documento_per_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id_email', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
                ('puerto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'email_correos',
            },
        ),
    ]
