# Generated by Django 5.0.7 on 2024-08-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='puerto',
            field=models.IntegerField(),
        ),
    ]
