# Generated by Django 5.0.7 on 2024-08-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_email_puerto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_factura',
            name='producto',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
