# Generated by Django 5.0.7 on 2024-08-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_detalle_factura_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_factura',
            name='id_producto_per',
            field=models.CharField(max_length=100),
        ),
    ]
